### ISSUE TITLE
VidyoIOSClient.Framework not available in SDK zip file.

### ISSUE THREAD

**Issue by gadregit** [Vidyo/helloworld-vidyo.io-ios#1]
Hi,

I have downloaded the latest SDK from the link, but when I unzip that folder the VidyoClientIOS.framework is not available in it.

In the demo video(https://www.youtube.com/watch?v=0YqTC4FLWcc) 
it says that we need to use Framework located at path VidyoClient-iOSSDK/lib/ios.

Also if I add all those .a(libraries) they are giving architectures missing error.

Please help.

**Comment by pfuternik** [comment]
Hello,

The VidyoClientIOS.framework will be included in the next version of our SDK (4.1.5.x), which will be released shortly. I have updated the documentation (README.md) with instructions on how to build using the libraries and third party frameworks. Please give it a shot and let me know if that gets you going.

Thanks,
Phil

**Comment by gadregit** [comment]
Hello,

I tried performing steps mentioned in README.md updated document. But its still giving me few architecture errors. Please find attached screenshots.
<img width="869" alt="framework-search-path" src="https://cloud.githubusercontent.com/assets/1226145/22415657/2d75aca6-e6ef-11e6-87a6-14ce6e016c1f.png">
<img width="869" alt="library-search-path" src="https://cloud.githubusercontent.com/assets/1226145/22415658/2d9159a6-e6ef-11e6-95d9-7ec8ddf7c5a1.png">
<img width="772" alt="header-search-path" src="https://cloud.githubusercontent.com/assets/1226145/22415659/2dae559c-e6ef-11e6-8a88-9484f9f832c1.png">
<img width="760" alt="architecture-error" src="https://cloud.githubusercontent.com/assets/1226145/22415660/2db9edf8-e6ef-11e6-9927-55b8ef81466d.png">





Thanks.
Amey Gadre.

**Comment by genegershanok** [comment]
Amey,

We currently don't support the emulator (x86_64). Please select a physical device as target. 

Thanks,

-gene

**Comment by gadregit** [comment]
Hi Gene,

Thanks for the help.
I was able to run the application.

But getting this error now for entitlements file. Let me know where would I be going wrong.
I checked the physical location, entitlements file does exist.
<img width="838" alt="screen shot 2017-01-30 at 11 51 01 pm" src="https://cloud.githubusercontent.com/assets/1226145/22435725/23d18758-e747-11e6-9eca-ececf49ff6a9.png">

**Comment by pfuternik** [comment]
Hi Amey,

The only way I was able to reproduce your error is if the entitlements file referenced is not in the exact directory specified. Sorry to ask, but have you triple checked that path? Is there perhaps another level of "DemoForVidyo" needed, i.e. "/Users/ameygadre/Desktop/DemoForVidyo/DemoForVidyo/DemoForVidyo.entitlements" ? The only other thing I can think of is if the file permissions are not allowing Xcode to read the file.

Best,
Phil

**Comment by pfuternik** [comment]
Hi Amey,

Just checking in. Were you able to successfully run the app?

Thanks,
Phil

**Comment by nagarajaghantasala** [comment]
![screen shot 2017-07-21 at 11 38 54 am](https://user-images.githubusercontent.com/30335349/28451272-ed8ae6ea-6e09-11e7-9ea7-f45aa0305f7c.png)

**Comment by nagarajaghantasala** [comment]
![screen shot 2017-07-21 at 11 38 54 am](https://user-images.githubusercontent.com/30335349/28451290-09633c3c-6e0a-11e7-8cbb-6388fc736483.png)

**Comment by nagarajaghantasala** [comment]
Hi,

Actually I am facing the above problem, If I build app after wrote **"$(PROJECT_DIR)/../SampleVideo.entitlements"** in Code Signing Entitlements in Build Settings .

Could you please help me from this problem.
