### ISSUE TITLE
IOS "Lmi/VidyoClient/VidyoConnector_Objc.h" Framework Import Problem

### ISSUE THREAD

**Issue by nagarajaghantasala** [Vidyo/helloworld-vidyo.io-ios#2]
Hi,

Actually I am facing framework import problem, If I build app after wrote "$(PROJECT_DIR)/../SampleVideo.entitlements" in Code Signing Entitlement
![screen shot 2017-07-21 at 1 41 35 pm](https://user-images.githubusercontent.com/30335349/28454883-76ec628c-6e1a-11e7-9b29-cc51597cc328.png)
![screen shot 2017-07-21 at 11 38 54 am](https://user-images.githubusercontent.com/30335349/28454882-76eb9aaa-6e1a-11e7-884a-58ffc4f554e8.png)
![screen shot 2017-07-21 at 12 33 17 pm](https://user-images.githubusercontent.com/30335349/28454884-76ef758a-6e1a-11e7-9a2d-96eb55ad883b.png)

s in Build Settings .

Could you please help me from this problem.

**Comment by pfuternik** [comment]
The import of the header file should have quotes : 

#import "Lmi/VidyoClient/VidyoConnector_Objc.h"

As for the entitlements file, in the settings, you are pointing to your Desktop as the location of the file. It should probably be in your SampleVideo directory. If you point to the proper location, that will solve this problem.

**Comment by nagarajaghantasala** [comment]
Thanks for your reply.

Actually, I am unable to find ".Entitlements" file  In my "Xcode Version 8.2.1".
How can I add this file, can you help me.

And I want "VidyoClientIOS.framework" in **IOS SWIFT language** for my project, Is there any availability...?

**Comment by pfuternik** [comment]
You can copy the VidyoIODemo.entitlements file from this project https://github.com/Vidyo/helloworld-vidyo.io-ios, add it to your Xcode project and reference it in your "Code Signing Entitlements" setting under Build Settings.

We do not have SWIFT language bindings in the framework yet, but you can still use that framework in your SWIFT project and make the Objective-C function calls. You would need to use a bridging header, which you can learn more about here: https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html

**Comment by nagarajaghantasala** [comment]
Still I am facing same problem.

I am sharing one url which have how I did Framework import into my project.
If you don't mind can you verify in below url video.

Please help me.

https://drive.google.com/open?id=0B-l8EzvwZLlqTURpWENVd2xrWm8

**Comment by pfuternik** [comment]
Please share your project with me (without VidyoClientIOS.framework) and let me know where the framework file should be placed. That would be the easiest way to determine the problem.

**Comment by nagarajaghantasala** [comment]
Okay, Here you can find the project.

https://drive.google.com/open?id=0B-l8EzvwZLlqU2tmaWZ3dmdEcXc

**Comment by pfuternik** [comment]
In build settings, change Code Signing Entitlements value 
   from : $(PROJECT_DIR)/../VidyoObjectiveC.entitlements
   to: $(PROJECT_DIR)/VidyoObjectiveC.entitlements

Then change Header Search Paths
   from : $(PROJECT_DIR)/../VidyoClientIOS.framework/Headers
   to : $(PROJECT_DIR)/VidyoClientIOS.framework/Headers

And that's all. VidyoClientIOS.framework should be in the same directory as VidyoObjectiveC.xcodeproj.

The ".." in the path takes you down a directory. So for example directory "/home/someName/../foo" is the equivalent to "home/foo". That was your problem.

**Comment by nagarajaghantasala** [comment]
Thank you so much, Its working fine for Objective C.

And for swift I Import "Lmi/VidyoClient/VidyoConnector_Objc.h" into my project Bridging Header.

After I compile this code, I am getting "Swift Compile Error"

Please check below images.

![screen shot 2017-07-25 at 12 31 11 pm](https://user-images.githubusercontent.com/30335349/28559979-667d82e0-7136-11e7-8eeb-61942c95dfd3.png)
![screen shot 2017-07-25 at 12 34 01 pm](https://user-images.githubusercontent.com/30335349/28559980-668026e4-7136-11e7-9925-bb809ca1b5b2.png)

**Comment by nagarajaghantasala** [comment]
Could you please provide any solution for me.

**Comment by pfuternik** [comment]
Try importing UIKit before importing the Vidyo header:

#import <UIKit/UIKit.h>

**Comment by nagarajaghantasala** [comment]
Thank you for your suggestion.

Now Importing framework is fine.

To initialize  VidyoClientConnector in ObjectiveC is " [VidyoClientConnector Initialize];"

In Swift I am unable to initialize  VidyoClientConnector.

If execute the code without initialization I am getting Exception Error.

Please verify in below screenshot.

![screen shot 2017-07-25 at 7 27 00 pm](https://user-images.githubusercontent.com/30335349/28575719-666d4234-716f-11e7-8515-82112316a24f.png)

**Comment by nagarajaghantasala** [comment]
Hi,

I am implementing new IOS Swift app which have requirement of Video Chat, to achieve this I want to use Vidyo.IO framework.
This link https://vidyo.io/ providing proper guidance to install and implement Vidyo.IO framework in ObjectiveC.

But, here I have no proper guidance to install and implement in Swift.

Actually, In my new project we have lot requirement on VideoChat.
So I am waiting for better way to implement Vidyo.IO framework in Swift.

Thanks

**Comment by JimmyNi** [comment]
Also waiting for the Vidyo.IO framework in Swift, have you figure out how to initialize the VidyoClientConnector yet?

**Comment by sachinVidyo** [comment]
Hi,
One of the very first calls you need to make to use the vidyo client connector is to call - 

`[VidyoClientConnector Initialize];`

If you want to use it in your swift project, that does create a problem, since when Xcode bridges the objective C code to swift it will change Initialize to initialize which is a reserved function. 

To get around this you can create an extension for VidyoClientConnector class with a different name for initialize - 

In your .h file - 

```
#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import <VidyoClientIOS.framework/Headers/Lmi/VidyoClient/VidyoConnector_Objc.h>

@interface VidyoClientConnector (VidyoIOBridge)
+(void) initializeVidyoClient;
@end
```

In your .m file - 

```
@implementation VidyoClientConnector (VidyoIOBridge)
+(void) initializeVidyoClient {
    [VidyoClientConnector Initialize];
}
@end
```

That ways in your swift code you can call - 

`VidyoClientConnector.initializeVidyoClient()`

and you are good to go. I will upload a sample on github soon.

**Comment by Zeeshan90** [comment]
having problem in implementing vidyo.io in swift project

**Comment by pfuternik** [comment]
We have a Swift reference application here: https://github.com/Vidyo/customview-swift-ios

If you have further questions, please email support@vidyo.io with the details of the issue that you are having and we'll be sure to help.

**Comment by Zeeshan90** [comment]
i am getting this error . i have imported the framework like written there
in readme

but still i am getting the error

VidyoClientIOS.framework/Headers/Lmi/VidyoClient/VidyoConnector_Objc.h'
file not found

**Comment by pfuternik** [comment]
You need to populate the Build Settings > Search Paths > Header Search Paths appropriately for the headers to be found. See the sample project as a reference.

**Comment by Zeeshan90** [comment]
I had done that.
I have checked the path for the header file that was correct according to the dir but still it didn’t find the path.

**Comment by pfuternik** [comment]
Please email support@vidyo.io in order to open a support ticket in regards to this, so we can better handle. If you can include a link where we can download your solution, that would be helpful.
